apiVersion: batch/v1
kind: Job
metadata:
  name: v2v
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: v2v
        image: quay.io/pkliczewski/v2v-job
        args: ["/v2v-dst", "disk", "example"]
        env:
        - name: "DEBUG"
          value: "1"
        securityContext:
          privileged: true
        volumeMounts:
        - name: volume-1
          mountPath: /v2v-dst
        - name: volume-2
          mountPath: /var/tmp
        - name: kvm
          mountPath: /dev/kvm
      volumes:
      - name: kvm
        hostPath:
          path: /dev/kvm
      - name: volume-1
        persistentVolumeClaim:
          claimName: $PVCNAME
      - name: volume-2
        persistentVolumeClaim:
          claimName: temp
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: $PVCNAME
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: $size
---
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: temp
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1100Mi